// import { Metadata } from "next";
// import { Inter } from "next/font/google";
// import React from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const Layout = ({ children }: { children: React.ReactNode }) => {
//   return (
//     // <div className="bg-slate-100 ">
//     //   <div className="container mx-auto">
//     //     <div className="flex flex-col items-center justify-between px-6 py-8 mx-auto max-w-[525px] h-screen ">
//     //       {children}
//     //     </div>
//     //   </div>
//     // </div>

// };

// export default Layout;
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "swiper/css";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import ToastProvider from "@/components/notification/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Authentication",
  description: "Authentication pages",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider> */}
        <ToastProvider>{children}</ToastProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
