import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "swiper/css";
import "./globals.css";
import Provider from "@/components/darkmode/Provider";
import Footer from "@/components/landingpage/Footer";
import Navbar from "@/components/landingpage/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider> */}
        <Navbar />
        {children}
        <Footer />
        {/* </Provider> */}
      </body>
    </html>
  );
}
