import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "swiper/css";
import "./globals.css";
import Provider from "@/components/darkmode/Provider";
import Footer from "@/components/landingpage/Footer";
import Navbar from "@/components/landingpage/Navbar/Navbar";
import ToastProvider from "@/components/notification/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kebayoran fresh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider> */}
        {/* <ToastProvider> */}
        <ToastProvider>
          <Navbar />
          {children}
          <Footer />
        </ToastProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
